INSERT INTO tb_user_app (name, email, password, por_number, birth_date, creat_At) VALUES ('Fábio Costa', 'fabiocosta@mail.com', '$2a$10$T0yoFdiWiA1HH/Oysq/ucOPr0hdu0dvlKk.hm8TH52WNn3l86wE6C', 'PT1234567', '1991-07-24', NOW());
INSERT INTO tb_user_app (name, email, password, por_number, birth_date, creat_At) VALUES ('Rabaioli', 'tfrabaioli@mail.com', '$2a$10$T0yoFdiWiA1HH/Oysq/ucOPr0hdu0dvlKk.hm8TH52WNn3l86wE6C', 'PT7654321', '1987-01-05', NOW());
INSERT INTO tb_user_app (name, email, password, por_number, birth_date, creat_At) VALUES ('David Morgado', 'davidmorgado@mail.com', '$2a$10$T0yoFdiWiA1HH/Oysq/ucOPr0hdu0dvlKk.hm8TH52WNn3l86wE6C', 'PT1122334', '1995-11-30', NOW());
INSERT INTO tb_user_app (name, email, password, por_number, birth_date, creat_At) VALUES ('José Tavares', 'josetavares@mail.com', '$2a$10$T0yoFdiWiA1HH/Oysq/ucOPr0hdu0dvlKk.hm8TH52WNn3l86wE6C', 'PT1719274', '1983-06-22', NOW());
INSERT INTO tb_user_app (name, email, password, por_number, birth_date, creat_At) VALUES ('Tiago Ferreira', 'tiagoferreira@mail.com', '$2a$10$T0yoFdiWiA1HH/Oysq/ucOPr0hdu0dvlKk.hm8TH52WNn3l86wE6C', 'PT3242077', '1993-01-24', NOW());
INSERT INTO tb_user_app (name, email, password, por_number, birth_date, creat_At) VALUES ('Alexandre Silva', 'alexandresilva@mail.com', '$2a$10$T0yoFdiWiA1HH/Oysq/ucOPr0hdu0dvlKk.hm8TH52WNn3l86wE6C', 'PT9199186', '1983-11-06', NOW());



INSERT INTO tb_role (authority) VALUES ('ROLE_VISITANTE');
INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_VIGILANTE');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');




-- 4 VIGILANTES (role_id = 3)

INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 3);
INSERT INTO tb_user_role (user_id, role_id) VALUES (4, 3);
INSERT INTO tb_user_role (user_id, role_id) VALUES (5, 3);
INSERT INTO tb_user_role (user_id, role_id) VALUES (6, 3);

-- 2 ADMINISTRADORES (role_id = 4)
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 4);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 4);


INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');

INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Auditório', 'Visitante Mateus Moreira', 'Chaves de casa (Sem porta chaves)', '2025-04-08', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/chavesdecasasemportachaves.png');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Piso 1 Sala de espera', 'Visitante Rodrigo Pinto', 'Chapeu Homem cor preta', '2025-02-20', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/bonepreto.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Recepção', 'Visitante Mariana Fernandes', 'Garrafa de agua perdida cor prateada', '2025-01-13', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/garrafadeaguaperdidametalica.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Cantina', 'Visitante Beatriz Lopes', 'Passaport Portugal - em nome de Catarina Santos', '2025-06-13', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/passaportportugal.JPG');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Elevador bloco B', 'Visitante Leonor Castro', 'Pasta com documentos em nome de José Silva', '2025-01-25', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/pastacomdocumentos.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Guilherme Rocha', 'Casaco preto com capuz', '2025-05-11', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/casacopreto.JPG');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Piso 2 WC Masculino', 'Visitante Lara Gomes', 'Telemovel Samsung cor rosa', '2025-06-04', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/samsungperdido.jfif');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Biblioteca', 'Visitante Ricardo Figueiredo', 'Conjunto chaves de casa com porta chave de couro', '2025-03-05', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/cavesdecasa.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Estacionamento', 'Visitante Catarina Ribeiro', 'Telemovel perdido cor preta', '2025-04-24', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/samsungpreto.webp');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Corredor central', 'Visitante Tomás Almeida', 'Relogio Prateado Perdido', '2025-01-08', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/relogioperdido.jfif');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Inês Carvalho', 'Objeto ', '2025-03-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/generico.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Cantina', 'Visitante João Matos', 'Relogio Adulto cor preta marca Swatch', '2025-02-02', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/relogioadultoperdido.webp');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Elevador bloco B', 'Visitante Sara Marques', 'Titulo de transporte em nome de Jair Silva', '2025-06-07', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/passeperdido2.webp');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Auditório', 'Visitante Rafael Sousa', 'Conjunto de chaves de casa ', '2025-07-11', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/cavesdecasa23.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Corredor central', 'Visitante Filipe Barros', 'Porta chave azul', '2025-05-15', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/portachavesazul.webp');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Piso 1 Sala de espera', 'Visitante Sofia Neves', 'Relogio Homem marca Rolex', '2025-03-28', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/relogiorolex.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Recepção', 'Visitante Diogo Ferreira', 'Relogio adulto preto pulseira laranja/preta', '2025-01-30', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/relogioadultoperdido2.jfif');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Biblioteca', 'Visitante Mariana Costa', 'Titulo de transporte em nome de Eduardo Martins', '2025-02-17', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/passeperdido.jfif');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Piso 2 WC Masculino', 'Visitante Bruno Martins', 'Relogio criança cor azul', '2025-03-09', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/relogiocriançaperdido.jpeg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Entrada principal', 'Visitante Carla Lima', 'Telemovel Iphone cor preta', '2025-04-20', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/iphoneperdido.webp');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Estacionamento', 'Visitante Hugo Teixeira', 'Passaporte Brasileiro em nome de Teresa Freitas ', '2025-06-26', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/passaporteperdido.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Cantina', 'Visitante Joana Vieira', 'Carteira castanha com documentos (Passaport) em nome de Sofia Pereira', '2025-05-03', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/walletbrownwithdocuments.jpeg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Biblioteca', 'Visitante Miguel Batista', 'Carteira preta com Documentos em nome de Jair Silva', '2025-06-18', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/carteirapretacomdocumentos.avif');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Elevador bloco B', 'Visitante Teresa Barata', 'Relógio de pulso prateado', '2025-07-07', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/relogioprateado.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Auditório', 'Visitante Daniel Morais', 'Carteira preta com cartões', '2025-04-27', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/carteirapreta.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Corredor central', 'Visitante Liliana Fonseca', 'Telemóvel Samsung azul', '2025-05-30', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/telemovelsamsungazulperdido.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Recepção', 'Visitante Ricardo Dias', 'Óculos de sol Ray-Ban', '2025-02-22', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/oculosdesolrayban.jfif');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Piso 1 Sala de espera', 'Visitante Vera Nogueira', 'Auriculares brancos', '2025-01-10', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/auricularesbranco.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Cantina', 'Visitante Nuno Pires', 'Carteira castanha com documentos', '2025-06-10', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/carteiracastanha.jpg');
INSERT INTO tb_item_lost (status, location, who_find, description, found_date, img_url) VALUES (true, 'Estacionamento', 'Visitante Andreia Leal', 'Chaves com porta-chaves azul', '2025-03-16', 'https://raw.githubusercontent.com/thiagorabaioli/assets/refs/heads/main/objetos%20perdidos/portachavesazul.webp');


INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 1, 1, 'Nota do pedido 1');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 2, 2, 'Nota do pedido 2');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 3, 3, 'Nota do pedido 3');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 4, 4, 'Nota do pedido 4');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 5, 1, 'Nota do pedido 5');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 6, 2, 'Nota do pedido 6');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 7, 3, 'Nota do pedido 7');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 8, 4, 'Nota do pedido 8');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 9, 1, 'Nota do pedido 9');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 10, 2, 'Nota do pedido 10');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 11, 3, 'Nota do pedido 11');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 12, 4, 'Nota do pedido 12');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 13, 1, 'Nota do pedido 13');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 14, 2, 'Nota do pedido 14');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 15, 3, 'Nota do pedido 15');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 16, 4, 'Nota do pedido 16');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 17, 1, 'Nota do pedido 17');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 18, 2, 'Nota do pedido 18');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 19, 3, 'Nota do pedido 19');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 20, 4, 'Nota do pedido 20');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-06', 21, 1, 'Nota do pedido 21');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-06', 22, 2, 'Nota do pedido 22');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-06', 23, 3, 'Nota do pedido 23');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-06', 24, 4, 'Nota do pedido 24');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-07', 25, 1, 'Nota do pedido 25');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-07', 26, 2, 'Nota do pedido 26');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-07', 27, 3, 'Nota do pedido 27');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-07', 28, 4, 'Nota do pedido 28');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-08', 29, 1, 'Nota do pedido 29');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-08', 30, 2, 'Nota do pedido 30');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-08', 31, 3, 'Nota do pedido 31');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-08', 32, 4, 'Nota do pedido 32');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-09', 33, 1, 'Nota do pedido 33');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-09', 34, 2, 'Nota do pedido 34');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-09', 35, 3, 'Nota do pedido 35');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-09', 36, 4, 'Nota do pedido 36');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-10', 37, 1, 'Nota do pedido 37');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-10', 38, 2, 'Nota do pedido 38');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-10', 39, 3, 'Nota do pedido 39');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-10', 40, 4, 'Nota do pedido 40');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 41, 1, 'Nota do pedido 41');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 42, 2, 'Nota do pedido 42');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 43, 3, 'Nota do pedido 43');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 44, 4, 'Nota do pedido 44');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 45, 1, 'Nota do pedido 45');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 46, 2, 'Nota do pedido 46');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 47, 3, 'Nota do pedido 47');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 48, 4, 'Nota do pedido 48');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 49, 1, 'Nota do pedido 49');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 50, 2, 'Nota do pedido 50');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 51, 3, 'Nota do pedido 51');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 52, 4, 'Nota do pedido 52');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 53, 1, 'Nota do pedido 53');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 54, 2, 'Nota do pedido 54');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 55, 3, 'Nota do pedido 55');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 56, 4, 'Nota do pedido 56');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 57, 1, 'Nota do pedido 57');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 58, 2, 'Nota do pedido 58');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 59, 3, 'Nota do pedido 59');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 60, 4, 'Nota do pedido 60');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-06', 61, 1, 'Nota do pedido 61');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-06', 62, 2, 'Nota do pedido 62');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-06', 63, 3, 'Nota do pedido 63');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-06', 64, 4, 'Nota do pedido 64');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-07', 65, 1, 'Nota do pedido 65');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-07', 66, 2, 'Nota do pedido 66');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-07', 67, 3, 'Nota do pedido 67');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-07', 68, 4, 'Nota do pedido 68');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-08', 69, 1, 'Nota do pedido 69');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-08', 70, 2, 'Nota do pedido 70');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-08', 71, 3, 'Nota do pedido 71');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-08', 72, 4, 'Nota do pedido 72');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-09', 73, 1, 'Nota do pedido 73');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-09', 74, 2, 'Nota do pedido 74');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-09', 75, 3, 'Nota do pedido 75');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-09', 76, 4, 'Nota do pedido 76');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-10', 77, 1, 'Nota do pedido 77');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-10', 78, 2, 'Nota do pedido 78');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-10', 79, 3, 'Nota do pedido 79');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-10', 80, 4, 'Nota do pedido 80');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 81, 1, 'Nota do pedido 81');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 82, 2, 'Nota do pedido 82');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 83, 3, 'Nota do pedido 83');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-01', 84, 4, 'Nota do pedido 84');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 85, 1, 'Nota do pedido 85');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 86, 2, 'Nota do pedido 86');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 87, 3, 'Nota do pedido 87');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-02', 88, 4, 'Nota do pedido 88');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 89, 1, 'Nota do pedido 89');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 90, 2, 'Nota do pedido 90');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 91, 3, 'Nota do pedido 91');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-03', 92, 4, 'Nota do pedido 92');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 93, 1, 'Nota do pedido 93');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 94, 2, 'Nota do pedido 94');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 95, 3, 'Nota do pedido 95');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-04', 96, 4, 'Nota do pedido 96');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 97, 1, 'Nota do pedido 97');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 98, 2, 'Nota do pedido 98');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 99, 3, 'Nota do pedido 99');
INSERT INTO ORDER_ITEM (type, interaction_date, item_lost_id, userapp_id, notes) VALUES (1, '2025-07-05', 100, 4, 'Nota do pedido 100');



